/**
 * SEC EDGAR ownership forms (3, 4, 5) → people.
 *
 * This is the free, official people source. Every officer and director of every
 * US public company files these, and the XML names them with their title. No
 * scraping, no vendor, no terms-of-service risk: it is a mandatory public
 * disclosure published by a government agency.
 *
 * What it yields per filing: the issuer (company, CIK, ticker) and one or more
 * reporting owners with their name, CIK, whether they are a director, an officer
 * or a 10% holder, and the officer's title as free text.
 *
 * WHAT IT DOES NOT YIELD
 *
 *   No email, no phone, no company domain. That is fine — this feeds
 *   discovery_profiles, which deliberately holds none of those. The address is
 *   resolved afterwards by lib/email-patterns from the company's domain, which
 *   has to come from somewhere else (the existing companies table, or a ticker
 *   lookup). Without a domain a profile is still searchable; it just cannot be
 *   revealed yet.
 *
 * TWO THINGS A NAIVE PARSER GETS WRONG
 *
 *   EDGAR conformed names are surname-first and upper-case: "COOK TIMOTHY D" is
 *   Timothy Cook. Reading them left to right produces a database full of people
 *   whose first and last names are swapped, which then breaks every email
 *   pattern inference downstream.
 *
 *   Many reporting owners are not people. Institutional 10% holders file the
 *   same forms, so "BLACKROCK INC." arrives shaped exactly like a human. Stored
 *   unfiltered they inflate the profile count with rows nobody can contact.
 *
 * XML handling is a narrow tag extractor rather than a DOM parse. That is a
 * deliberate trade: these documents are machine-generated by EDGAR against a
 * fixed, shallow schema, and avoiding the dependency keeps this module pure and
 * runnable anywhere the rest of lib/ runs.
 */

import { normalizeTitle, type NormalizedTitle } from "./title-ontology";

// ─── XML extraction ──────────────────────────────────────────

const decodeEntities = (value: string): string =>
  value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&amp;/g, "&"); // last, so &amp;lt; does not double-decode

/** First value of `tag`, searching only within `scope`. */
function tagValue(scope: string, tag: string): string | null {
  const match = scope.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, "i"));
  if (!match) return null;
  const value = decodeEntities(match[1]).trim();
  return value === "" ? null : value;
}

/** Every occurrence of a block-level tag, as raw inner XML. */
function tagBlocks(scope: string, tag: string): string[] {
  const out: string[] = [];
  const pattern = new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, "gi");
  for (const match of scope.matchAll(pattern)) out.push(match[1]);
  return out;
}

/**
 * EDGAR wraps some values in <value> elements:
 *   <officerTitle><value>CEO</value></officerTitle>
 * and sometimes writes them bare. Accept both.
 */
function flagOrValue(scope: string, tag: string): string | null {
  const block = tagValue(scope, tag);
  if (block === null) return null;
  const inner = tagValue(block, "value");
  return inner ?? block;
}

const isTrue = (value: string | null): boolean =>
  value !== null && ["1", "true", "y", "yes"].includes(value.trim().toLowerCase());

// ─── Entity detection ────────────────────────────────────────

/**
 * Tokens that mean a reporting owner is an organisation.
 *
 * Institutional holders file the same forms as executives, so this is the only
 * thing standing between a profile pool of decision makers and one padded with
 * asset managers. Erring toward excluding is correct: a missed person costs one
 * row, a stored fund pollutes every count built on the table.
 */
const ENTITY_TOKENS = new Set([
  "inc", "incorporated", "corp", "corporation", "co", "company", "llc", "lc",
  "llp", "lp", "plc", "ltd", "limited", "gmbh", "ag", "nv", "bv", "sa", "ab",
  "oy", "as", "pte", "pty", "kk", "sarl", "spa", "srl",
  "trust", "trusts", "fund", "funds", "foundation", "endowment", "institute",
  "partners", "partnership", "holdings", "holding", "group", "groupe",
  "capital", "management", "mgmt", "advisors", "advisers", "advisory",
  "associates", "asset", "assets", "investments", "investment", "investors",
  "ventures", "venture", "equity", "equities", "securities", "financial",
  "bancorp", "bank", "banking", "insurance", "assurance", "reinsurance",
  "international", "worldwide", "global", "enterprises", "industries",
  "systems", "technologies", "solutions", "services", "brands", "labs",
  "committee", "association", "society", "union", "council", "authority",
  "pac", "plan", "esop", "ira", "lllp", "gp",
]);

/** Phrases that mark an organisation regardless of tokenisation. */
const ENTITY_PHRASES = [
  /\bl\.?\s?p\.?$/i,
  /\bl\.?\s?l\.?\s?c\.?$/i,
  /\b(family|living|revocable|irrevocable|charitable|grantor|remainder)\s+trust\b/i,
  /\bet\s+al\b/i,
  /\b(and|&)\s+co\b/i,
  /\b\d{4}\b/, // vintage funds: "Sequoia Capital Fund 2019"
];

/**
 * Is this reporting owner an organisation rather than a person?
 *
 * `relationship` refines the name test rather than replacing it: a 10% holder
 * that is neither a director nor an officer is usually a fund even when its name
 * looks personal (a founder's own holding vehicle, say).
 */
export function looksLikeEntity(
  name: string,
  relationship?: { isDirector?: boolean; isOfficer?: boolean; isTenPercentOwner?: boolean },
): boolean {
  const cleaned = name.trim();
  if (!cleaned) return true;

  if (ENTITY_PHRASES.some((pattern) => pattern.test(cleaned))) return true;

  const tokens = cleaned
    .toLowerCase()
    .replace(/[.,]/g, " ")
    .split(/\s+/)
    .filter(Boolean);
  if (tokens.some((token) => ENTITY_TOKENS.has(token))) return true;

  // A holder with no board seat and no office is an investor, not an operator.
  // Keep it out of a pool meant for prospecting even if the name reads human.
  if (
    relationship?.isTenPercentOwner === true &&
    relationship.isDirector !== true &&
    relationship.isOfficer !== true
  ) {
    return true;
  }

  // A single token is never a usable person record here.
  return tokens.length < 2;
}

// ─── Name handling ───────────────────────────────────────────

const NAME_SUFFIXES = new Set([
  "jr", "sr", "ii", "iii", "iv", "v", "vi",
  "md", "phd", "dds", "dvm", "esq", "cpa", "cfa", "mba", "jd", "rn",
]);

/**
 * Surname particles, which belong to the surname rather than starting the
 * given names. Without these, "VAN DER HOEVEN JAN" yields the surname "Van" and
 * the first name "Der".
 */
const SURNAME_PARTICLES = new Set([
  "van", "von", "de", "del", "della", "der", "den", "di", "da", "dos", "das",
  "la", "le", "les", "du", "ter", "ten", "op", "af", "av",
  "bin", "ibn", "binte", "bint", "al", "el", "abu", "abd",
  "mc", "mac", "st", "saint", "san", "santa", "santos",
]);

/** Capitalise a name token, respecting apostrophes, hyphens and Mc/Mac. */
function titleCaseToken(token: string): string {
  const lower = token.toLowerCase();

  const capitalise = (s: string) => (s ? s[0].toUpperCase() + s.slice(1) : s);

  // Split on separators and capitalise each part: o'brien → O'Brien,
  // smith-jones → Smith-Jones.
  const parts = lower.split(/(['\-])/);
  let out = parts.map((p, i) => (i % 2 === 1 ? p : capitalise(p))).join("");

  // McDonald, MacArthur — but not "Mac" alone, and not Mack/Macy.
  const mc = out.match(/^(Mc)([a-z])(.+)$/);
  if (mc) out = `${mc[1]}${mc[2].toUpperCase()}${mc[3]}`;
  const mac = out.match(/^(Mac)([a-z])(.{3,})$/);
  if (mac) out = `${mac[1]}${mac[2].toUpperCase()}${mac[3]}`;

  return out;
}

export interface SplitName {
  firstName: string | null;
  lastName: string | null;
  middleName: string | null;
  suffix: string | null;
}

/**
 * Split an EDGAR conformed name into parts.
 *
 * Handles both shapes EDGAR produces:
 *   "COOK TIMOTHY D"   surname first, space separated
 *   "Cook, Timothy D"  surname first, comma separated
 *
 * A comma is authoritative when present — it removes the ambiguity entirely, so
 * it is checked before any positional heuristic.
 */
export function splitEdgarName(raw: string): SplitName {
  const empty: SplitName = { firstName: null, lastName: null, middleName: null, suffix: null };
  const cleaned = raw.replace(/\s+/g, " ").trim();
  if (!cleaned) return empty;

  const assemble = (surnameTokens: string[], givenTokens: string[], suffix: string | null): SplitName => {
    const lastName = surnameTokens.map(titleCaseToken).join(" ") || null;
    const firstName = givenTokens.length ? titleCaseToken(givenTokens[0]) : null;
    const middleName = givenTokens.length > 1
      ? givenTokens.slice(1).map(titleCaseToken).join(" ")
      : null;
    return { firstName, lastName, middleName, suffix };
  };

  const pullSuffix = (tokens: string[]): { tokens: string[]; suffix: string | null } => {
    let suffix: string | null = null;
    const out = [...tokens];
    while (out.length > 1) {
      const candidate = out[out.length - 1].replace(/\./g, "").toLowerCase();
      if (!NAME_SUFFIXES.has(candidate)) break;
      suffix = titleCaseToken(out.pop()!);
    }
    return { tokens: out, suffix };
  };

  // Comma form: everything before the comma is the surname.
  if (cleaned.includes(",")) {
    const [surnamePart, ...rest] = cleaned.split(",");
    const givenRaw = rest.join(" ").trim().split(" ").filter(Boolean);
    const { tokens: given, suffix } = pullSuffix(givenRaw);
    const surname = surnamePart.trim().split(" ").filter(Boolean);
    if (surname.length === 0) return empty;
    return assemble(surname, given, suffix);
  }

  const { tokens, suffix } = pullSuffix(cleaned.split(" ").filter(Boolean));
  if (tokens.length === 0) return empty;
  if (tokens.length === 1) {
    return { firstName: null, lastName: titleCaseToken(tokens[0]), middleName: null, suffix };
  }

  // Space form: consume leading surname particles, then the surname proper.
  let cut = 0;
  while (cut < tokens.length - 1 && SURNAME_PARTICLES.has(tokens[cut].replace(/\./g, "").toLowerCase())) {
    cut++;
  }
  const surname = tokens.slice(0, cut + 1);
  const given = tokens.slice(cut + 1);

  // Particles consumed everything — treat the whole string as a surname rather
  // than inventing a first name from a particle.
  if (given.length === 0) return { firstName: null, lastName: surname.map(titleCaseToken).join(" "), middleName: null, suffix };

  return assemble(surname, given, suffix);
}

// ─── Parsing a filing ────────────────────────────────────────

export interface EdgarIssuer {
  cik: string | null;
  name: string | null;
  tradingSymbol: string | null;
}

export interface EdgarReportingOwner {
  cik: string | null;
  /** Exactly as EDGAR published it, never discarded. */
  rawName: string;
  firstName: string | null;
  lastName: string | null;
  middleName: string | null;
  suffix: string | null;
  isDirector: boolean;
  isOfficer: boolean;
  isTenPercentOwner: boolean;
  isOther: boolean;
  officerTitle: string | null;
  /** The title actually used for normalisation — see `effectiveTitle`. */
  resolvedTitle: string | null;
  normalizedTitle: NormalizedTitle | null;
  city: string | null;
  state: string | null;
  isEntity: boolean;
}

export interface EdgarOwnershipFiling {
  formType: string | null;
  periodOfReport: string | null;
  issuer: EdgarIssuer;
  owners: EdgarReportingOwner[];
}

/**
 * The title to normalise for a reporting owner.
 *
 * A director with no officer title gets "Board Member", not "Director". The
 * title ontology ranks a bare "Director" in the mid-management band, which is
 * right for "Director of Marketing" and badly wrong for someone who sits on the
 * board — it would bury the highest-value contacts in a pool below VPs.
 *
 * When someone is both, the officer title wins: a CEO who also holds a board
 * seat is reached as a CEO.
 */
export function effectiveTitle(owner: {
  officerTitle?: string | null;
  isOfficer?: boolean;
  isDirector?: boolean;
  isTenPercentOwner?: boolean;
}): string | null {
  const title = owner.officerTitle?.trim();
  if (title) return title;
  if (owner.isDirector) return "Board Member";
  if (owner.isOfficer) return "Officer";
  if (owner.isTenPercentOwner) return "Shareholder";
  return null;
}

/** Parse one ownership form (3, 4 or 5) XML document. */
export function parseOwnershipForm(xml: string): EdgarOwnershipFiling | null {
  if (!xml || !/<ownershipDocument[\s>]/i.test(xml)) return null;

  const doc = tagValue(xml, "ownershipDocument") ?? xml;
  const issuerBlock = tagValue(doc, "issuer") ?? "";

  const issuer: EdgarIssuer = {
    cik: normalizeCik(tagValue(issuerBlock, "issuerCik")),
    name: tagValue(issuerBlock, "issuerName"),
    tradingSymbol: tagValue(issuerBlock, "issuerTradingSymbol"),
  };

  const owners: EdgarReportingOwner[] = [];

  for (const block of tagBlocks(doc, "reportingOwner")) {
    const idBlock = tagValue(block, "reportingOwnerId") ?? block;
    const addressBlock = tagValue(block, "reportingOwnerAddress") ?? "";
    const relBlock = tagValue(block, "reportingOwnerRelationship") ?? "";

    const rawName = tagValue(idBlock, "rptOwnerName");
    if (!rawName) continue;

    const isDirector = isTrue(flagOrValue(relBlock, "isDirector"));
    const isOfficer = isTrue(flagOrValue(relBlock, "isOfficer"));
    const isTenPercentOwner = isTrue(flagOrValue(relBlock, "isTenPercentOwner"));
    const isOther = isTrue(flagOrValue(relBlock, "isOther"));
    const officerTitle = flagOrValue(relBlock, "officerTitle");

    const isEntity = looksLikeEntity(rawName, { isDirector, isOfficer, isTenPercentOwner });
    const split = isEntity
      ? { firstName: null, lastName: null, middleName: null, suffix: null }
      : splitEdgarName(rawName);

    const resolvedTitle = effectiveTitle({
      officerTitle,
      isOfficer,
      isDirector,
      isTenPercentOwner,
    });

    owners.push({
      cik: normalizeCik(tagValue(idBlock, "rptOwnerCik")),
      rawName,
      ...split,
      isDirector,
      isOfficer,
      isTenPercentOwner,
      isOther,
      officerTitle,
      resolvedTitle,
      normalizedTitle: resolvedTitle ? normalizeTitle(resolvedTitle) : null,
      city: tagValue(addressBlock, "rptOwnerCity"),
      state: tagValue(addressBlock, "rptOwnerState"),
      isEntity,
    });
  }

  return {
    formType: tagValue(doc, "documentType"),
    periodOfReport: tagValue(doc, "periodOfReport"),
    issuer,
    owners,
  };
}

/** EDGAR CIKs are zero-padded to ten digits in some places and bare in others. */
export function normalizeCik(value: string | null): string | null {
  if (!value) return null;
  const digits = value.replace(/\D/g, "");
  if (!digits) return null;
  return digits.replace(/^0+/, "").padStart(10, "0");
}

// ─── Archive URLs and locations ──────────────────────────────

/**
 * The machine-readable XML for a filing in the EDGAR archive.
 *
 * `primaryDocument` from the submissions API is sometimes the XSL-rendered view,
 * which EDGAR places in an `xslF345X0...` subdirectory. The raw XML sits under
 * the same filename without that prefix, so the last path segment is correct in
 * both cases. A non-XML primary document (an HTML-only filing) has no parseable
 * counterpart and yields null rather than a URL that 404s.
 */
export function filingXmlUrl(
  cik: string,
  accessionNumber: string,
  primaryDocument: string,
): string | null {
  const digits = cik.replace(/\D/g, "").replace(/^0+/, "");
  const accession = accessionNumber.replace(/[^0-9]/g, "");
  const file = (primaryDocument || "").split("/").pop() ?? "";
  if (!digits || !accession || !file.toLowerCase().endsWith(".xml")) return null;
  return `https://www.sec.gov/Archives/edgar/data/${digits}/${accession}/${file}`;
}

/**
 * EDGAR writes US states and foreign countries into the same two-letter field,
 * so a bare code is ambiguous until checked against the state list.
 */
const US_STATES: ReadonlySet<string> = new Set([
  "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID",
  "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO",
  "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA",
  "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
  "PR", "VI", "GU", "AS", "MP",
]);

export interface EdgarLocation {
  countryCode: string | null;
  region: string | null;
}

/**
 * Country and region for a business address.
 *
 * `stateOrCountry` holding "CA" means California, not Canada — EDGAR is a US
 * filing system and its own state codes win. Resolving it as a country would
 * relocate a large share of US companies abroad, and country is the primary
 * search filter.
 */
export function resolveEdgarLocation(
  address: { stateOrCountry?: string | null; country?: string | null } | null | undefined,
  toCountry: (value: string | null) => string | null,
): EdgarLocation {
  const stateOrCountry = (address?.stateOrCountry ?? "").trim().toUpperCase();

  if (US_STATES.has(stateOrCountry)) return { countryCode: "US", region: stateOrCountry };

  const explicit = toCountry(address?.country ?? null);
  if (explicit) return { countryCode: explicit, region: null };

  const inferred = toCountry(stateOrCountry || null);
  if (inferred) return { countryCode: inferred, region: null };

  return { countryCode: null, region: stateOrCountry || null };
}

/** Is this owner worth storing as a prospect? */
export function isUsableOwner(owner: EdgarReportingOwner): { usable: boolean; reason?: string } {
  if (owner.isEntity) return { usable: false, reason: "not_a_person" };
  if (!owner.lastName) return { usable: false, reason: "no_name" };
  if (!owner.firstName) return { usable: false, reason: "no_given_name" };
  if (!owner.resolvedTitle) return { usable: false, reason: "no_role" };
  return { usable: true };
}
