import { CheckSquare, Loader2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useState } from "react";
import { useLinkedinTasks, useUpdateLinkedinTask } from "@/hooks/use-linkedin-campaigns";

export default function LinkedinTasksPage() {
  const [status, setStatus] = useState("pending");
  const { data: tasks, isLoading } = useLinkedinTasks({ status });
  const updateTask = useUpdateLinkedinTask();

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      <div className="flex items-start gap-3">
        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-sky-500/10 text-sky-600">
          <CheckSquare className="h-5 w-5" />
        </div>
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">LinkedIn Tasks</h1>
          <p className="text-sm text-muted-foreground mt-0.5">Manual tasks generated by your LinkedIn campaigns.</p>
        </div>
      </div>

      <Tabs value={status} onValueChange={setStatus}>
        <TabsList>
          <TabsTrigger value="pending">Pending</TabsTrigger>
          <TabsTrigger value="in_progress">In Progress</TabsTrigger>
          <TabsTrigger value="done">Done</TabsTrigger>
          <TabsTrigger value="skipped">Skipped</TabsTrigger>
        </TabsList>
      </Tabs>

      <Card>
        {isLoading ? <div className="p-6"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div> :
          !tasks?.length ? <div className="p-12 text-center text-sm text-muted-foreground">No {status.replace("_", " ")} tasks.</div> : (
            <Table>
              <TableHeader><TableRow>
                <TableHead className="text-xs">Task</TableHead>
                <TableHead className="text-xs">Contact</TableHead>
                <TableHead className="text-xs">Campaign</TableHead>
                <TableHead className="text-xs">Type</TableHead>
                <TableHead className="text-xs">Due</TableHead>
                <TableHead className="text-xs w-32"></TableHead>
              </TableRow></TableHeader>
              <TableBody>
                {tasks.map((t: any) => (
                  <TableRow key={t.id}>
                    <TableCell className="text-sm">
                      <p className="font-medium">{t.title}</p>
                      {t.description && <p className="text-[11px] text-muted-foreground truncate max-w-[300px]">{t.description}</p>}
                    </TableCell>
                    <TableCell className="text-xs">{t.contacts?.first_name} {t.contacts?.last_name}</TableCell>
                    <TableCell className="text-xs">{t.linkedin_campaigns?.name || "—"}</TableCell>
                    <TableCell><Badge variant="outline" className="text-[10px] capitalize">{t.task_type?.replace("_", " ")}</Badge></TableCell>
                    <TableCell className="text-xs">{t.due_at ? new Date(t.due_at).toLocaleDateString() : "—"}</TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        {status !== "done" && <Button size="sm" variant="outline" className="h-7 text-[11px]" onClick={() => updateTask.mutate({ id: t.id, status: "done", completed_at: new Date().toISOString() })}>Done</Button>}
                        {status === "pending" && <Button size="sm" variant="outline" className="h-7 text-[11px]" onClick={() => updateTask.mutate({ id: t.id, status: "skipped" })}>Skip</Button>}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
      </Card>
    </div>
  );
}
